In [20]:
import numpy as np
import math

In [28]:
a=np.random.randn(5)

In [29]:
def softmax_handcoded_1d(array_input):
    return np.exp(array_input)/sum(np.exp(array_input))

In [30]:
sm=softmax_handcoded_1d(a)

In [31]:
sm

array([0.03971125, 0.08796009, 0.08399891, 0.74707438, 0.04125537])

In [32]:
sum(sm)

0.9999999999999998

In [26]:
a_matrix=np.random.randn(5, 3)

In [27]:
a_matrix

array([[ 0.30487153, -1.22890101,  0.26919497],
       [-0.70388964, -0.02337425,  0.20225253],
       [ 1.11732269,  0.08298799, -0.26150122],
       [-1.68122943,  0.8687523 ,  1.94699547],
       [-0.29894562,  2.45009268,  0.82577262]])

array([-0.65483451, -0.52501136,  0.93880946,  1.13451834,  2.97691968])

In [44]:
def softmax_handcoded_2d(array_input):
    exp_a= np.exp(array_input)
    return np.exp(array_input)/exp_a.sum(axis=1).reshape(-1, 1)

In [45]:
sm=softmax_handcoded_2d(a_matrix)

In [47]:
sm.sum(axis=1)

array([1., 1., 1., 1., 1.])