In [2]:
from sklearn import datasets
import pandas as pd
iris = datasets.load_iris()

In [3]:
X=pd.DataFrame(iris.data)

In [4]:
y=pd.DataFrame(iris.target)

In [5]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

Y = pd.get_dummies(y1).values

F:\Anaconda\envs\tf-gpu\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [8]:
Y


array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
X

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
5    5.4  3.9  1.7  0.4
6    4.6  3.4  1.4  0.3
7    5.0  3.4  1.5  0.2
8    4.4  2.9  1.4  0.2
9    4.9  3.1  1.5  0.1
10   5.4  3.7  1.5  0.2
11   4.8  3.4  1.6  0.2
12   4.8  3.0  1.4  0.1
13   4.3  3.0  1.1  0.1
14   5.8  4.0  1.2  0.2
15   5.7  4.4  1.5  0.4
16   5.4  3.9  1.3  0.4
17   5.1  3.5  1.4  0.3
18   5.7  3.8  1.7  0.3
19   5.1  3.8  1.5  0.3
20   5.4  3.4  1.7  0.2
21   5.1  3.7  1.5  0.4
22   4.6  3.6  1.0  0.2
23   5.1  3.3  1.7  0.5
24   4.8  3.4  1.9  0.2
25   5.0  3.0  1.6  0.2
26   5.0  3.4  1.6  0.4
27   5.2  3.5  1.5  0.2
28   5.2  3.4  1.4  0.2
29   4.7  3.2  1.6  0.2
..   ...  ...  ...  ...
120  6.9  3.2  5.7  2.3
121  5.6  2.8  4.9  2.0
122  7.7  2.8  6.7  2.0
123  6.3  2.7  4.9  1.8
124  6.7  3.3  5.7  2.1
125  7.2  3.2  6.0  1.8
126  6.2  2.8  4.8  1.8
127  6.1  3.0  4.9  1.8
128  6.4  2.8  5.6  2.1
129  7.2  3.0  5.8  1.6
130  7.4  2.8  6.1  1.9
131  7.9  3.8  6.4  2.0
132  6.4  2.8  5.6  2.2
133  6.3  2.8  5.1  1.5
134  6.1  2.6  5.6  1.4
135  7.7  3.0  6.1  2.3
136  6.3  3.4  5.6  2.4
137  6.4  3.1  5.5  1.8
138  6.0  3.0  4.8  1.8
139  6.9  3.1  5.4  2.1
140  6.7  3.1  5.6  2.4
141  6.9  3.1  5.1  2.3
142  5.8  2.7  5.1  1.9
143  6.8  3.2  5.9  2.3
144  6.7  3.3  5.7  2.5
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [12]:
import keras

from keras.models import Sequential
from keras.layers import Dense

classifier=Sequential()

Using TensorFlow backend.


In [13]:
classifier.add(Dense(8, input_dim=4, activation='relu'))

classifier.add(Dense(3, activation='softmax'))



In [14]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics = ['accuracy'])
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)



Epoch 1/100
120/120 [==============================] - 12s 96ms/step - loss: 0.6543 - acc: 0.6806
Epoch 2/100
120/120 [==============================] - 0s 543us/step - loss: 0.6339 - acc: 0.7000
Epoch 3/100
120/120 [==============================] - 0s 460us/step - loss: 0.6144 - acc: 0.7306
Epoch 4/100
120/120 [==============================] - 0s 537us/step - loss: 0.5962 - acc: 0.7500
Epoch 5/100
120/120 [==============================] - 0s 456us/step - loss: 0.5778 - acc: 0.7583
Epoch 6/100
120/120 [==============================] - 0s 456us/step - loss: 0.5601 - acc: 0.7611
Epoch 7/100
120/120 [==============================] - 0s 451us/step - loss: 0.5428 - acc: 0.7667
Epoch 8/100
120/120 [==============================] - 0s 473us/step - loss: 0.5253 - acc: 0.7694
Epoch 9/100
120/120 [==============================] - 0s 512us/step - loss: 0.5082 - acc: 0.7722
Epoch 10/100
120/120 [==============================] - 0s 546us/step - loss: 0.4925 - acc: 0.7778
Epoch 11/100
120/12

120/120 [==============================] - 0s 451us/step - loss: 0.1335 - acc: 0.9556
Epoch 84/100
120/120 [==============================] - 0s 460us/step - loss: 0.1322 - acc: 0.9583
Epoch 85/100
120/120 [==============================] - 0s 568us/step - loss: 0.1307 - acc: 0.9583
Epoch 86/100
120/120 [==============================] - 0s 551us/step - loss: 0.1292 - acc: 0.9583
Epoch 87/100
120/120 [==============================] - 0s 451us/step - loss: 0.1278 - acc: 0.9583
Epoch 88/100
120/120 [==============================] - 0s 378us/step - loss: 0.1264 - acc: 0.9583
Epoch 89/100
120/120 [==============================] - 0s 478us/step - loss: 0.1252 - acc: 0.9583
Epoch 90/100
120/120 [==============================] - 0s 426us/step - loss: 0.1237 - acc: 0.9583
Epoch 91/100
120/120 [==============================] - 0s 418us/step - loss: 0.1224 - acc: 0.9583
Epoch 92/100
120/120 [==============================] - 0s 418us/step - loss: 0.1211 - acc: 0.9583
Epoch 93/100
120/120 [=

In [15]:
ypred=classifier.predict(X_test)

In [18]:
import numpy as np
ypred_max=np.argmax(ypred, axis=1)

In [19]:
ypred_max

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0], dtype=int64)

In [22]:
y_test_max=np.argmax(y_test, axis=1)

In [23]:
y_test_max

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0], dtype=int64)

In [24]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_max,ypred_max))
print(confusion_matrix(y_test_max,ypred_max))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        11
          1       1.00      1.00      1.00        13
          2       1.00      1.00      1.00         6

avg / total       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [25]:
def baseline_model():
    classifier=Sequential()
    classifier.add(Dense(8, input_dim=4, activation='relu'))
    classifier.add(Dense(3, activation='softmax'))
    classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics = ['accuracy'])
    return classifier


In [26]:
from keras.wrappers.scikit_learn import KerasClassifier

In [27]:
estimator=KerasClassifier(build_fn=baseline_model, epochs=200, batch_size=10)

In [28]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold

In [29]:
kfold=KFold(n_splits=10, shuffle=True, random_state=10)
results=cross_val_score(estimator, X_train, y_train, cv=kfold)

Epoch 1/200
108/108 [==============================] - 0s 4ms/step - loss: 0.6985 - acc: 0.5247
Epoch 2/200
108/108 [==============================] - 0s 501us/step - loss: 0.6739 - acc: 0.5432
Epoch 3/200
108/108 [==============================] - 0s 446us/step - loss: 0.6526 - acc: 0.5617
Epoch 4/200
108/108 [==============================] - 0s 492us/step - loss: 0.6320 - acc: 0.5772
Epoch 5/200
108/108 [==============================] - 0s 506us/step - loss: 0.6136 - acc: 0.5926
Epoch 6/200
108/108 [==============================] - 0s 455us/step - loss: 0.5956 - acc: 0.6019
Epoch 7/200
108/108 [==============================] - 0s 446us/step - loss: 0.5792 - acc: 0.6173
Epoch 8/200
108/108 [==============================] - 0s 473us/step - loss: 0.5618 - acc: 0.6296
Epoch 9/200
108/108 [==============================] - 0s 492us/step - loss: 0.5447 - acc: 0.6327
Epoch 10/200
108/108 [==============================] - 0s 557us/step - loss: 0.5285 - acc: 0.6698
Epoch 11/200
108/108 

108/108 [==============================] - 0s 511us/step - loss: 0.1771 - acc: 0.9228
Epoch 84/200
108/108 [==============================] - 0s 483us/step - loss: 0.1756 - acc: 0.9228
Epoch 85/200
108/108 [==============================] - 0s 529us/step - loss: 0.1743 - acc: 0.9259
Epoch 86/200
108/108 [==============================] - 0s 492us/step - loss: 0.1729 - acc: 0.9259
Epoch 87/200
108/108 [==============================] - 0s 483us/step - loss: 0.1717 - acc: 0.9259
Epoch 88/200
108/108 [==============================] - 0s 419us/step - loss: 0.1702 - acc: 0.9259
Epoch 89/200
108/108 [==============================] - 0s 487us/step - loss: 0.1689 - acc: 0.9259
Epoch 90/200
108/108 [==============================] - 0s 464us/step - loss: 0.1675 - acc: 0.9290
Epoch 91/200
108/108 [==============================] - 0s 492us/step - loss: 0.1667 - acc: 0.9290
Epoch 92/200
108/108 [==============================] - 0s 483us/step - loss: 0.1651 - acc: 0.9290
Epoch 93/200
108/108 [=

108/108 [==============================] - 0s 501us/step - loss: 0.0947 - acc: 0.9630
Epoch 166/200
108/108 [==============================] - 0s 538us/step - loss: 0.0941 - acc: 0.9630
Epoch 167/200
108/108 [==============================] - 0s 576us/step - loss: 0.0934 - acc: 0.9630
Epoch 168/200
108/108 [==============================] - 0s 603us/step - loss: 0.0927 - acc: 0.9630
Epoch 169/200
108/108 [==============================] - 0s 548us/step - loss: 0.0921 - acc: 0.9630
Epoch 170/200
108/108 [==============================] - 0s 557us/step - loss: 0.0916 - acc: 0.9630
Epoch 171/200
108/108 [==============================] - 0s 529us/step - loss: 0.0908 - acc: 0.9630
Epoch 172/200
108/108 [==============================] - 0s 538us/step - loss: 0.0902 - acc: 0.9630
Epoch 173/200
108/108 [==============================] - 0s 566us/step - loss: 0.0895 - acc: 0.9630
Epoch 174/200
108/108 [==============================] - 0s 603us/step - loss: 0.0890 - acc: 0.9630
Epoch 175/200


108/108 [==============================] - 0s 511us/step - loss: 0.1679 - acc: 0.9537
Epoch 47/200
108/108 [==============================] - 0s 501us/step - loss: 0.1652 - acc: 0.9537
Epoch 48/200
108/108 [==============================] - 0s 538us/step - loss: 0.1628 - acc: 0.9537
Epoch 49/200
108/108 [==============================] - 0s 483us/step - loss: 0.1604 - acc: 0.9537
Epoch 50/200
108/108 [==============================] - 0s 473us/step - loss: 0.1582 - acc: 0.9537
Epoch 51/200
108/108 [==============================] - 0s 492us/step - loss: 0.1556 - acc: 0.9537
Epoch 52/200
108/108 [==============================] - 0s 548us/step - loss: 0.1535 - acc: 0.9537
Epoch 53/200
108/108 [==============================] - 0s 566us/step - loss: 0.1514 - acc: 0.9537
Epoch 54/200
108/108 [==============================] - 0s 501us/step - loss: 0.1491 - acc: 0.9568
Epoch 55/200
108/108 [==============================] - 0s 511us/step - loss: 0.1471 - acc: 0.9568
Epoch 56/200
108/108 [=

108/108 [==============================] - 0s 418us/step - loss: 0.0653 - acc: 0.9722
Epoch 129/200
108/108 [==============================] - 0s 399us/step - loss: 0.0648 - acc: 0.9753
Epoch 130/200
108/108 [==============================] - 0s 436us/step - loss: 0.0644 - acc: 0.9753
Epoch 131/200
108/108 [==============================] - 0s 464us/step - loss: 0.0640 - acc: 0.9753
Epoch 132/200
108/108 [==============================] - 0s 408us/step - loss: 0.0635 - acc: 0.9753
Epoch 133/200
108/108 [==============================] - 0s 408us/step - loss: 0.0633 - acc: 0.9753
Epoch 134/200
108/108 [==============================] - 0s 418us/step - loss: 0.0626 - acc: 0.9753
Epoch 135/200
108/108 [==============================] - 0s 418us/step - loss: 0.0624 - acc: 0.9753
Epoch 136/200
108/108 [==============================] - 0s 427us/step - loss: 0.0619 - acc: 0.9753
Epoch 137/200
108/108 [==============================] - 0s 408us/step - loss: 0.0616 - acc: 0.9753
Epoch 138/200


108/108 [==============================] - 0s 408us/step - loss: 0.5680 - acc: 0.6636
Epoch 10/200
108/108 [==============================] - 0s 408us/step - loss: 0.5427 - acc: 0.7130
Epoch 11/200
108/108 [==============================] - 0s 408us/step - loss: 0.5196 - acc: 0.7531
Epoch 12/200
108/108 [==============================] - 0s 408us/step - loss: 0.4977 - acc: 0.7747
Epoch 13/200
108/108 [==============================] - 0s 418us/step - loss: 0.4783 - acc: 0.7901
Epoch 14/200
108/108 [==============================] - 0s 399us/step - loss: 0.4585 - acc: 0.8056
Epoch 15/200
108/108 [==============================] - 0s 408us/step - loss: 0.4412 - acc: 0.8302
Epoch 16/200
108/108 [==============================] - 0s 427us/step - loss: 0.4244 - acc: 0.8519
Epoch 17/200
108/108 [==============================] - 0s 408us/step - loss: 0.4085 - acc: 0.8673
Epoch 18/200
108/108 [==============================] - 0s 418us/step - loss: 0.3942 - acc: 0.8735
Epoch 19/200
108/108 [=

108/108 [==============================] - 0s 408us/step - loss: 0.1074 - acc: 0.9691
Epoch 92/200
108/108 [==============================] - 0s 446us/step - loss: 0.1065 - acc: 0.9691
Epoch 93/200
108/108 [==============================] - 0s 418us/step - loss: 0.1050 - acc: 0.9691
Epoch 94/200
108/108 [==============================] - 0s 436us/step - loss: 0.1040 - acc: 0.9691
Epoch 95/200
108/108 [==============================] - 0s 427us/step - loss: 0.1030 - acc: 0.9691
Epoch 96/200
108/108 [==============================] - 0s 408us/step - loss: 0.1018 - acc: 0.9691
Epoch 97/200
108/108 [==============================] - 0s 436us/step - loss: 0.1008 - acc: 0.9691
Epoch 98/200
108/108 [==============================] - 0s 418us/step - loss: 0.0995 - acc: 0.9691
Epoch 99/200
108/108 [==============================] - 0s 418us/step - loss: 0.0985 - acc: 0.9691
Epoch 100/200
108/108 [==============================] - 0s 613us/step - loss: 0.0978 - acc: 0.9691
Epoch 101/200
108/108 

108/108 [==============================] - 0s 483us/step - loss: 0.0570 - acc: 0.9815
Epoch 173/200
108/108 [==============================] - 0s 492us/step - loss: 0.0565 - acc: 0.9815
Epoch 174/200
108/108 [==============================] - 0s 439us/step - loss: 0.0564 - acc: 0.9815
Epoch 175/200
108/108 [==============================] - 0s 482us/step - loss: 0.0562 - acc: 0.9815
Epoch 176/200
108/108 [==============================] - 0s 483us/step - loss: 0.0558 - acc: 0.9815
Epoch 177/200
108/108 [==============================] - 0s 483us/step - loss: 0.0554 - acc: 0.9815
Epoch 178/200
108/108 [==============================] - 0s 501us/step - loss: 0.0555 - acc: 0.9815
Epoch 179/200
108/108 [==============================] - 0s 520us/step - loss: 0.0550 - acc: 0.9815
Epoch 180/200
108/108 [==============================] - 0s 511us/step - loss: 0.0547 - acc: 0.9815
Epoch 181/200
108/108 [==============================] - 0s 529us/step - loss: 0.0545 - acc: 0.9815
Epoch 182/200


108/108 [==============================] - 0s 473us/step - loss: 0.2346 - acc: 0.9105
Epoch 55/200
108/108 [==============================] - 0s 492us/step - loss: 0.2306 - acc: 0.9105
Epoch 56/200
108/108 [==============================] - 0s 446us/step - loss: 0.2269 - acc: 0.9105
Epoch 57/200
108/108 [==============================] - 0s 473us/step - loss: 0.2230 - acc: 0.9105
Epoch 58/200
108/108 [==============================] - 0s 446us/step - loss: 0.2191 - acc: 0.9105
Epoch 59/200
108/108 [==============================] - 0s 473us/step - loss: 0.2158 - acc: 0.9105
Epoch 60/200
108/108 [==============================] - 0s 441us/step - loss: 0.2118 - acc: 0.9105
Epoch 61/200
108/108 [==============================] - 0s 468us/step - loss: 0.2085 - acc: 0.9136
Epoch 62/200
108/108 [==============================] - 0s 483us/step - loss: 0.2053 - acc: 0.9136
Epoch 63/200
108/108 [==============================] - 0s 501us/step - loss: 0.2018 - acc: 0.9136
Epoch 64/200
108/108 [=

108/108 [==============================] - 0s 464us/step - loss: 0.0798 - acc: 0.9630
Epoch 137/200
108/108 [==============================] - 0s 511us/step - loss: 0.0794 - acc: 0.9630
Epoch 138/200
108/108 [==============================] - 0s 464us/step - loss: 0.0788 - acc: 0.9660
Epoch 139/200
108/108 [==============================] - 0s 520us/step - loss: 0.0782 - acc: 0.9660
Epoch 140/200
108/108 [==============================] - 0s 483us/step - loss: 0.0778 - acc: 0.9660
Epoch 141/200
108/108 [==============================] - 0s 492us/step - loss: 0.0772 - acc: 0.9660
Epoch 142/200
108/108 [==============================] - 0s 501us/step - loss: 0.0767 - acc: 0.9660
Epoch 143/200
108/108 [==============================] - 0s 455us/step - loss: 0.0765 - acc: 0.9660
Epoch 144/200
108/108 [==============================] - 0s 464us/step - loss: 0.0758 - acc: 0.9660
Epoch 145/200
108/108 [==============================] - 0s 473us/step - loss: 0.0753 - acc: 0.9691
Epoch 146/200


108/108 [==============================] - 0s 455us/step - loss: 0.4802 - acc: 0.7623
Epoch 18/200
108/108 [==============================] - 0s 473us/step - loss: 0.4687 - acc: 0.7623
Epoch 19/200
108/108 [==============================] - 0s 464us/step - loss: 0.4580 - acc: 0.7654
Epoch 20/200
108/108 [==============================] - 0s 455us/step - loss: 0.4467 - acc: 0.7654
Epoch 21/200
108/108 [==============================] - 0s 446us/step - loss: 0.4364 - acc: 0.7840
Epoch 22/200
108/108 [==============================] - 0s 501us/step - loss: 0.4255 - acc: 0.7932
Epoch 23/200
108/108 [==============================] - 0s 462us/step - loss: 0.4153 - acc: 0.7994
Epoch 24/200
108/108 [==============================] - 0s 455us/step - loss: 0.4054 - acc: 0.8179
Epoch 25/200
108/108 [==============================] - 0s 455us/step - loss: 0.3958 - acc: 0.8241
Epoch 26/200
108/108 [==============================] - 0s 458us/step - loss: 0.3865 - acc: 0.8302
Epoch 27/200
108/108 [=

108/108 [==============================] - 0s 455us/step - loss: 0.1696 - acc: 0.9228
Epoch 100/200
108/108 [==============================] - 0s 483us/step - loss: 0.1684 - acc: 0.9228
Epoch 101/200
108/108 [==============================] - 0s 473us/step - loss: 0.1674 - acc: 0.9228
Epoch 102/200
108/108 [==============================] - 0s 455us/step - loss: 0.1665 - acc: 0.9228
Epoch 103/200
108/108 [==============================] - 0s 446us/step - loss: 0.1652 - acc: 0.9228
Epoch 104/200
108/108 [==============================] - 0s 455us/step - loss: 0.1643 - acc: 0.9228
Epoch 105/200
108/108 [==============================] - 0s 455us/step - loss: 0.1631 - acc: 0.9228
Epoch 106/200
108/108 [==============================] - 0s 464us/step - loss: 0.1626 - acc: 0.9259
Epoch 107/200
108/108 [==============================] - 0s 455us/step - loss: 0.1608 - acc: 0.9259
Epoch 108/200
108/108 [==============================] - 0s 464us/step - loss: 0.1599 - acc: 0.9259
Epoch 109/200


108/108 [==============================] - 0s 464us/step - loss: 0.0961 - acc: 0.9691
Epoch 182/200
108/108 [==============================] - 0s 455us/step - loss: 0.0954 - acc: 0.9691
Epoch 183/200
108/108 [==============================] - 0s 492us/step - loss: 0.0947 - acc: 0.9691
Epoch 184/200
108/108 [==============================] - 0s 455us/step - loss: 0.0942 - acc: 0.9691
Epoch 185/200
108/108 [==============================] - 0s 455us/step - loss: 0.0937 - acc: 0.9691
Epoch 186/200
108/108 [==============================] - 0s 464us/step - loss: 0.0928 - acc: 0.9691
Epoch 187/200
108/108 [==============================] - 0s 455us/step - loss: 0.0925 - acc: 0.9691
Epoch 188/200
108/108 [==============================] - 0s 464us/step - loss: 0.0917 - acc: 0.9691
Epoch 189/200
108/108 [==============================] - 0s 443us/step - loss: 0.0914 - acc: 0.9691
Epoch 190/200
108/108 [==============================] - 0s 473us/step - loss: 0.0905 - acc: 0.9691
Epoch 191/200


108/108 [==============================] - 0s 446us/step - loss: 0.1886 - acc: 0.9136
Epoch 64/200
108/108 [==============================] - 0s 464us/step - loss: 0.1876 - acc: 0.9167
Epoch 65/200
108/108 [==============================] - 0s 430us/step - loss: 0.1863 - acc: 0.9167
Epoch 66/200
108/108 [==============================] - 0s 550us/step - loss: 0.1851 - acc: 0.9167
Epoch 67/200
108/108 [==============================] - 0s 473us/step - loss: 0.1839 - acc: 0.9167
Epoch 68/200
108/108 [==============================] - 0s 557us/step - loss: 0.1827 - acc: 0.9198
Epoch 69/200
108/108 [==============================] - 0s 473us/step - loss: 0.1816 - acc: 0.9198
Epoch 70/200
108/108 [==============================] - 0s 455us/step - loss: 0.1805 - acc: 0.9198
Epoch 71/200
108/108 [==============================] - 0s 464us/step - loss: 0.1794 - acc: 0.9228
Epoch 72/200
108/108 [==============================] - 0s 455us/step - loss: 0.1782 - acc: 0.9228
Epoch 73/200
108/108 [=

108/108 [==============================] - 0s 511us/step - loss: 0.1024 - acc: 0.9568
Epoch 146/200
108/108 [==============================] - 0s 501us/step - loss: 0.1014 - acc: 0.9599
Epoch 147/200
108/108 [==============================] - 0s 483us/step - loss: 0.1002 - acc: 0.9660
Epoch 148/200
108/108 [==============================] - 0s 446us/step - loss: 0.0991 - acc: 0.9630
Epoch 149/200
108/108 [==============================] - 0s 492us/step - loss: 0.0982 - acc: 0.9630
Epoch 150/200
108/108 [==============================] - 0s 557us/step - loss: 0.0970 - acc: 0.9630
Epoch 151/200
108/108 [==============================] - 0s 529us/step - loss: 0.0959 - acc: 0.9630
Epoch 152/200
108/108 [==============================] - 0s 826us/step - loss: 0.0951 - acc: 0.9691
Epoch 153/200
108/108 [==============================] - 0s 780us/step - loss: 0.0943 - acc: 0.9630
Epoch 154/200
108/108 [==============================] - 0s 854us/step - loss: 0.0931 - acc: 0.9630
Epoch 155/200


108/108 [==============================] - 0s 464us/step - loss: 0.4150 - acc: 0.8025
Epoch 27/200
108/108 [==============================] - 0s 483us/step - loss: 0.4074 - acc: 0.8025
Epoch 28/200
108/108 [==============================] - 0s 446us/step - loss: 0.4004 - acc: 0.8056
Epoch 29/200
108/108 [==============================] - 0s 492us/step - loss: 0.3929 - acc: 0.8241
Epoch 30/200
108/108 [==============================] - 0s 492us/step - loss: 0.3863 - acc: 0.8333
Epoch 31/200
108/108 [==============================] - 0s 492us/step - loss: 0.3793 - acc: 0.8395
Epoch 32/200
108/108 [==============================] - 0s 462us/step - loss: 0.3723 - acc: 0.8426
Epoch 33/200
108/108 [==============================] - 0s 553us/step - loss: 0.3659 - acc: 0.8457
Epoch 34/200
108/108 [==============================] - 0s 501us/step - loss: 0.3589 - acc: 0.8519
Epoch 35/200
108/108 [==============================] - 0s 491us/step - loss: 0.3526 - acc: 0.8580
Epoch 36/200
108/108 [=

108/108 [==============================] - 0s 464us/step - loss: 0.1390 - acc: 0.9568
Epoch 109/200
108/108 [==============================] - 0s 483us/step - loss: 0.1375 - acc: 0.9599
Epoch 110/200
108/108 [==============================] - 0s 410us/step - loss: 0.1365 - acc: 0.9599
Epoch 111/200
108/108 [==============================] - 0s 501us/step - loss: 0.1353 - acc: 0.9599
Epoch 112/200
108/108 [==============================] - 0s 473us/step - loss: 0.1339 - acc: 0.9599
Epoch 113/200
108/108 [==============================] - 0s 464us/step - loss: 0.1330 - acc: 0.9599
Epoch 114/200
108/108 [==============================] - 0s 464us/step - loss: 0.1315 - acc: 0.9599
Epoch 115/200
108/108 [==============================] - 0s 464us/step - loss: 0.1305 - acc: 0.9599
Epoch 116/200
108/108 [==============================] - 0s 473us/step - loss: 0.1295 - acc: 0.9599
Epoch 117/200
108/108 [==============================] - 0s 455us/step - loss: 0.1282 - acc: 0.9630
Epoch 118/200


108/108 [==============================] - 0s 492us/step - loss: 0.0756 - acc: 0.9691
Epoch 191/200
108/108 [==============================] - 0s 455us/step - loss: 0.0750 - acc: 0.9691
Epoch 192/200
108/108 [==============================] - 0s 492us/step - loss: 0.0746 - acc: 0.9691
Epoch 193/200
108/108 [==============================] - 0s 464us/step - loss: 0.0741 - acc: 0.9691
Epoch 194/200
108/108 [==============================] - 0s 520us/step - loss: 0.0739 - acc: 0.9691
Epoch 195/200
108/108 [==============================] - 0s 492us/step - loss: 0.0732 - acc: 0.9691
Epoch 196/200
108/108 [==============================] - 0s 501us/step - loss: 0.0728 - acc: 0.9691
Epoch 197/200
108/108 [==============================] - 0s 492us/step - loss: 0.0724 - acc: 0.9691
Epoch 198/200
108/108 [==============================] - 0s 529us/step - loss: 0.0719 - acc: 0.9691
Epoch 199/200
108/108 [==============================] - 0s 511us/step - loss: 0.0716 - acc: 0.9691
Epoch 200/200


108/108 [==============================] - 0s 501us/step - loss: 0.1762 - acc: 0.9228
Epoch 73/200
108/108 [==============================] - 0s 501us/step - loss: 0.1744 - acc: 0.9228
Epoch 74/200
108/108 [==============================] - 0s 464us/step - loss: 0.1731 - acc: 0.9228
Epoch 75/200
108/108 [==============================] - 0s 501us/step - loss: 0.1716 - acc: 0.9228
Epoch 76/200
108/108 [==============================] - 0s 501us/step - loss: 0.1703 - acc: 0.9259
Epoch 77/200
108/108 [==============================] - 0s 501us/step - loss: 0.1689 - acc: 0.9259
Epoch 78/200
108/108 [==============================] - 0s 492us/step - loss: 0.1674 - acc: 0.9259
Epoch 79/200
108/108 [==============================] - 0s 492us/step - loss: 0.1660 - acc: 0.9290
Epoch 80/200
108/108 [==============================] - 0s 492us/step - loss: 0.1646 - acc: 0.9290
Epoch 81/200
108/108 [==============================] - 0s 478us/step - loss: 0.1633 - acc: 0.9321
Epoch 82/200
108/108 [=

108/108 [==============================] - 0s 566us/step - loss: 0.0865 - acc: 0.9722
Epoch 155/200
108/108 [==============================] - 0s 520us/step - loss: 0.0859 - acc: 0.9722
Epoch 156/200
108/108 [==============================] - 0s 483us/step - loss: 0.0852 - acc: 0.9722
Epoch 157/200
108/108 [==============================] - 0s 483us/step - loss: 0.0847 - acc: 0.9722
Epoch 158/200
108/108 [==============================] - 0s 492us/step - loss: 0.0841 - acc: 0.9722
Epoch 159/200
108/108 [==============================] - 0s 483us/step - loss: 0.0835 - acc: 0.9722
Epoch 160/200
108/108 [==============================] - 0s 473us/step - loss: 0.0829 - acc: 0.9722
Epoch 161/200
108/108 [==============================] - 0s 464us/step - loss: 0.0823 - acc: 0.9722
Epoch 162/200
108/108 [==============================] - 0s 464us/step - loss: 0.0819 - acc: 0.9722
Epoch 163/200
108/108 [==============================] - 0s 473us/step - loss: 0.0813 - acc: 0.9722
Epoch 164/200


Epoch 36/200
108/108 [==============================] - 0s 483us/step - loss: 0.2174 - acc: 0.9074
Epoch 37/200
108/108 [==============================] - 0s 483us/step - loss: 0.2143 - acc: 0.9105
Epoch 38/200
108/108 [==============================] - 0s 455us/step - loss: 0.2114 - acc: 0.9105
Epoch 39/200
108/108 [==============================] - 0s 464us/step - loss: 0.2084 - acc: 0.9105
Epoch 40/200
108/108 [==============================] - 0s 457us/step - loss: 0.2060 - acc: 0.9105
Epoch 41/200
108/108 [==============================] - 0s 483us/step - loss: 0.2033 - acc: 0.9105
Epoch 42/200
108/108 [==============================] - 0s 511us/step - loss: 0.2004 - acc: 0.9105
Epoch 43/200
108/108 [==============================] - 0s 483us/step - loss: 0.1983 - acc: 0.9136
Epoch 44/200
108/108 [==============================] - 0s 464us/step - loss: 0.1954 - acc: 0.9136
Epoch 45/200
108/108 [==============================] - 0s 464us/step - loss: 0.1931 - acc: 0.9136
Epoch 46/2

108/108 [==============================] - 0s 520us/step - loss: 0.0940 - acc: 0.9691
Epoch 119/200
108/108 [==============================] - 0s 483us/step - loss: 0.0934 - acc: 0.9691
Epoch 120/200
108/108 [==============================] - 0s 492us/step - loss: 0.0926 - acc: 0.9691
Epoch 121/200
108/108 [==============================] - 0s 492us/step - loss: 0.0919 - acc: 0.9691
Epoch 122/200
108/108 [==============================] - 0s 520us/step - loss: 0.0911 - acc: 0.9691
Epoch 123/200
108/108 [==============================] - 0s 492us/step - loss: 0.0906 - acc: 0.9691
Epoch 124/200
108/108 [==============================] - 0s 511us/step - loss: 0.0898 - acc: 0.9691
Epoch 125/200
108/108 [==============================] - 0s 492us/step - loss: 0.0892 - acc: 0.9691
Epoch 126/200
108/108 [==============================] - 0s 492us/step - loss: 0.0887 - acc: 0.9691
Epoch 127/200
108/108 [==============================] - 0s 473us/step - loss: 0.0879 - acc: 0.9691
Epoch 128/200


12/12 [==============================] - 0s 8ms/step
Epoch 1/200
108/108 [==============================] - 0s 4ms/step - loss: 0.8466 - acc: 0.5370
Epoch 2/200
108/108 [==============================] - 0s 559us/step - loss: 0.8117 - acc: 0.5432
Epoch 3/200
108/108 [==============================] - 0s 455us/step - loss: 0.7766 - acc: 0.5525
Epoch 4/200
108/108 [==============================] - 0s 455us/step - loss: 0.7457 - acc: 0.5586
Epoch 5/200
108/108 [==============================] - 0s 464us/step - loss: 0.7166 - acc: 0.5648
Epoch 6/200
108/108 [==============================] - 0s 475us/step - loss: 0.6886 - acc: 0.5741
Epoch 7/200
108/108 [==============================] - 0s 494us/step - loss: 0.6619 - acc: 0.5895
Epoch 8/200
108/108 [==============================] - 0s 464us/step - loss: 0.6360 - acc: 0.6173
Epoch 9/200
108/108 [==============================] - 0s 473us/step - loss: 0.6117 - acc: 0.6358
Epoch 10/200
108/108 [==============================] - 0s 446us/st

108/108 [==============================] - 0s 464us/step - loss: 0.1839 - acc: 0.9259
Epoch 83/200
108/108 [==============================] - 0s 473us/step - loss: 0.1820 - acc: 0.9290
Epoch 84/200
108/108 [==============================] - 0s 455us/step - loss: 0.1804 - acc: 0.9290
Epoch 85/200
108/108 [==============================] - 0s 473us/step - loss: 0.1785 - acc: 0.9290
Epoch 86/200
108/108 [==============================] - 0s 455us/step - loss: 0.1765 - acc: 0.9290
Epoch 87/200
108/108 [==============================] - 0s 466us/step - loss: 0.1750 - acc: 0.9321
Epoch 88/200
108/108 [==============================] - 0s 470us/step - loss: 0.1733 - acc: 0.9321
Epoch 89/200
108/108 [==============================] - 0s 479us/step - loss: 0.1715 - acc: 0.9321
Epoch 90/200
108/108 [==============================] - 0s 464us/step - loss: 0.1699 - acc: 0.9352
Epoch 91/200
108/108 [==============================] - 0s 455us/step - loss: 0.1681 - acc: 0.9352
Epoch 92/200
108/108 [=

108/108 [==============================] - 0s 464us/step - loss: 0.0851 - acc: 0.9630
Epoch 165/200
108/108 [==============================] - 0s 492us/step - loss: 0.0846 - acc: 0.9630
Epoch 166/200
108/108 [==============================] - 0s 473us/step - loss: 0.0839 - acc: 0.9630
Epoch 167/200
108/108 [==============================] - 0s 420us/step - loss: 0.0832 - acc: 0.9630
Epoch 168/200
108/108 [==============================] - 0s 520us/step - loss: 0.0827 - acc: 0.9630
Epoch 169/200
108/108 [==============================] - 0s 464us/step - loss: 0.0823 - acc: 0.9630
Epoch 170/200
108/108 [==============================] - 0s 464us/step - loss: 0.0815 - acc: 0.9630
Epoch 171/200
108/108 [==============================] - 0s 455us/step - loss: 0.0811 - acc: 0.9691
Epoch 172/200
108/108 [==============================] - 0s 473us/step - loss: 0.0803 - acc: 0.9691
Epoch 173/200
108/108 [==============================] - 0s 483us/step - loss: 0.0797 - acc: 0.9691
Epoch 174/200


In [30]:
print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Baseline: 96.67% (2.72%)


In [31]:
results

array([1.        , 1.        , 0.94444445, 0.9444445 , 0.94444445,
       0.9444445 , 0.9444445 , 0.9444445 , 1.        , 1.        ])