In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset=pd.read_csv("Churn_Modelling.csv")

X=dataset.iloc[:, 3:13].values
y=dataset.iloc[:, 13].values


from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])


onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X=X[:, 1:]


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
import tensorflow as tf
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

import keras


from keras.models import Sequential
from keras.layers import Dense

classifier=Sequential()

classifier.add(Dense(6, kernel_initializer='uniform', input_dim=11, activation='relu'))

classifier.add(Dense(6, activation='relu',  kernel_initializer='uniform'))

classifier.add(Dense(1, activation='sigmoid', kernel_initializer='uniform'))
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics = ['accuracy'])


classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

ypred=classifier.predict(X_test)

In [49]:
ypred

array([[ 0.19668563],
       [ 0.17973517],
       [ 0.21107771],
       ..., 
       [ 0.24225001],
       [ 0.12653372],
       [ 0.14809442]], dtype=float32)

In [50]:
ypred = (ypred > 0.5)

In [51]:
ypred

array([[False],
       [False],
       [False],
       ..., 
       [False],
       [False],
       [False]], dtype=bool)

In [52]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, ypred)

In [53]:
cm

array([[1525,   70],
       [ 236,  169]])

In [54]:
X_test.shape

(2000, 11)

In [105]:
X_pred_single=np.array([100, 'Spain', 'Male', 20, 0, 0, 0, 0, 0, 0])

In [106]:
K=pd.DataFrame(X_pred_single.reshape(1, -1))

In [107]:
K=K.iloc[:, :].values

In [108]:
K[:, 1] = labelencoder_X_1.transform(K[:, 1])

In [95]:
K[:, 2] = labelencoder_X_2.transform(K[:, 2])

In [96]:

K = onehotencoder.transform(K).toarray()
K=K[:, 1:]

In [97]:
sc.transform(K)
K.shape

(1, 11)

In [98]:

ypred=classifier.predict(K)

In [99]:
(ypred[0]>0.5)

array([False], dtype=bool)

In [70]:
K

array([[  0.00000000e+00,   0.00000000e+00,   6.00000000e+02,
          1.00000000e+00,   4.00000000e+01,   2.00000000e+00,
          6.00000000e+03,   2.00000000e+00,   1.00000000e+00,
          1.00000000e+00,   5.00000000e+04]])

In [109]:
K

array([['100', 2, 'Male', '20', '0', '0', '0', '0', '0', '0']], dtype=object)

In [2]:
import keras


from keras.models import Sequential
from keras.layers import Dense



#classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

#ypred=classifier.predict(X_test)

Using TensorFlow backend.


In [2]:

def build_classifier():
    classifier=Sequential()
    classifier.add(Dense(6, kernel_initializer='uniform', input_dim=11, activation='relu'))
    classifier.add(Dense(6, activation='relu',  kernel_initializer='uniform'))
    classifier.add(Dense(1, activation='sigmoid', kernel_initializer='uniform'))
    classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics = ['accuracy'])
    return classifier


In [ ]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

classifier=KerasClassifier(build_fn=build_classifier, batch_size = 10, epochs = 50)
accuracies=cross_val_score(estimator=classifier, X=X_train, y=y_train, cv=2, n_jobs=-1)

Using TensorFlow backend.


In [6]:
accuracies

array([ 0.83999999,  0.84624999,  0.8725    ,  0.8275    ,  0.85624999,
        0.82875   ,  0.85999999,  0.83374999,  0.81375   ,  0.84374999])

In [7]:
accuracies.mean()

0.84224999498575914

In [8]:
accuracies.std()

0.016534055095404059

In [13]:
accuracies.shape

(10,)

In [14]:
import numpy as np
np.sort(accuracies)

array([ 0.81375   ,  0.8275    ,  0.82875   ,  0.83374999,  0.83999999,
        0.84374999,  0.84624999,  0.85624999,  0.85999999,  0.8725    ])

In [15]:
import tensorflow as tf


import keras


from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

classifier=Sequential()

classifier.add(Dense(6, kernel_initializer='uniform', input_dim=11, activation='relu'))
classifier.add(Dropout(p=0.1))

classifier.add(Dense(6, activation='relu',  kernel_initializer='uniform'))
classifier.add(Dropout(p=0.1))

classifier.add(Dense(1, activation='sigmoid', kernel_initializer='uniform'))
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics = ['accuracy'])


classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

ypred=classifier.predict(X_test)

/Users/maxim/anaconda3/envs/tensorflow/lib/python2.7/site-packages/ipykernel_launcher.py:14: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  
/Users/maxim/anaconda3/envs/tensorflow/lib/python2.7/site-packages/ipykernel_launcher.py:17: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`


Epoch 1/100
8000/8000 [==============================] - 2s 280us/step - loss: 0.4985 - acc: 0.7955
Epoch 2/100
8000/8000 [==============================] - 2s 274us/step - loss: 0.4400 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 265us/step - loss: 0.4372 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 265us/step - loss: 0.4350 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 2s 287us/step - loss: 0.4342 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 2s 295us/step - loss: 0.4337 - acc: 0.7960
Epoch 7/100
8000/8000 [==============================] - 3s 322us/step - loss: 0.4325 - acc: 0.7960
Epoch 8/100
8000/8000 [==============================] - 2s 301us/step - loss: 0.4306 - acc: 0.7960
Epoch 9/100
8000/8000 [==============================] - 3s 313us/step - loss: 0.4304 - acc: 0.7961
Epoch 10/100
8000/8000 [==============================] - 3s 338us/step - loss: 0.4306 - acc: 0.8141

In [4]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

import tensorflow as tf


import keras


from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

def build_classifier1(optimizer):
    classifier=Sequential()
    classifier.add(Dense(6, kernel_initializer='uniform', input_dim=11, activation='relu'))
    classifier.add(Dropout(p=0.1))
    classifier.add(Dense(6, activation='relu',  kernel_initializer='uniform'))
    classifier.add(Dropout(p=0.1))
    classifier.add(Dense(1, activation='sigmoid', kernel_initializer='uniform'))
    classifier.add(Dropout(p=0.1))
    classifier.compile(optimizer=optimizer, loss='binary_crossentropy', metrics = ['accuracy'])
    return classifier

classifier=KerasClassifier(build_fn=build_classifier1, batch_size = 10, epochs = 50)


In [ ]:
parameters={'batch_size':[25, 32],
           'epochs':[50, 250],
           'optimizer':['adam', 'rmsprop']}

grid_search=GridSearchCV(estimator=classifier, param_grid=parameters, scoring='accuracy', cv=10)
grid_search.fit(X_train, y_train)

F:\Anaconda\envs\tf-gpu\lib\site-packages\ipykernel_launcher.py:18: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
F:\Anaconda\envs\tf-gpu\lib\site-packages\ipykernel_launcher.py:20: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
F:\Anaconda\envs\tf-gpu\lib\site-packages\ipykernel_launcher.py:22: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`


Epoch 1/50
