In [2]:
from sklearn import datasets
import pandas as pd
iris = datasets.load_iris()

In [3]:
X=pd.DataFrame(iris.data)

In [4]:
y=pd.DataFrame(iris.target)

In [5]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

Y = pd.get_dummies(y1).values

F:\Anaconda\envs\tf-gpu\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [8]:
Y


array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
X

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
5    5.4  3.9  1.7  0.4
6    4.6  3.4  1.4  0.3
7    5.0  3.4  1.5  0.2
8    4.4  2.9  1.4  0.2
9    4.9  3.1  1.5  0.1
10   5.4  3.7  1.5  0.2
11   4.8  3.4  1.6  0.2
12   4.8  3.0  1.4  0.1
13   4.3  3.0  1.1  0.1
14   5.8  4.0  1.2  0.2
15   5.7  4.4  1.5  0.4
16   5.4  3.9  1.3  0.4
17   5.1  3.5  1.4  0.3
18   5.7  3.8  1.7  0.3
19   5.1  3.8  1.5  0.3
20   5.4  3.4  1.7  0.2
21   5.1  3.7  1.5  0.4
22   4.6  3.6  1.0  0.2
23   5.1  3.3  1.7  0.5
24   4.8  3.4  1.9  0.2
25   5.0  3.0  1.6  0.2
26   5.0  3.4  1.6  0.4
27   5.2  3.5  1.5  0.2
28   5.2  3.4  1.4  0.2
29   4.7  3.2  1.6  0.2
..   ...  ...  ...  ...
120  6.9  3.2  5.7  2.3
121  5.6  2.8  4.9  2.0
122  7.7  2.8  6.7  2.0
123  6.3  2.7  4.9  1.8
124  6.7  3.3  5.7  2.1
125  7.2  3.2  6.0  1.8
126  6.2  2.8  4.8  1.8
127  6.1  3.0  4.9  1.8
128  6.4  2.8  5.6  2.1
129  7.2  3.0  5.8  1.6
130  7.4  2.8  6.1  1.9
131  7.9  3.8  6.4  2.0
132  6.4  2.8  5.6  2.2
133  6.3  2.8  5.1  1.5
134  6.1  2.6  5.6  1.4
135  7.7  3.0  6.1  2.3
136  6.3  3.4  5.6  2.4
137  6.4  3.1  5.5  1.8
138  6.0  3.0  4.8  1.8
139  6.9  3.1  5.4  2.1
140  6.7  3.1  5.6  2.4
141  6.9  3.1  5.1  2.3
142  5.8  2.7  5.1  1.9
143  6.8  3.2  5.9  2.3
144  6.7  3.3  5.7  2.5
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [12]:
import keras

from keras.models import Sequential
from keras.layers import Dense

classifier=Sequential()

Using TensorFlow backend.


In [13]:
classifier.add(Dense(8, input_dim=4, activation='relu'))

classifier.add(Dense(3, activation='softmax'))



In [14]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics = ['accuracy'])
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)



Epoch 1/100
120/120 [==============================] - 12s 96ms/step - loss: 0.6543 - acc: 0.6806
Epoch 2/100
120/120 [==============================] - 0s 543us/step - loss: 0.6339 - acc: 0.7000
Epoch 3/100
120/120 [==============================] - 0s 460us/step - loss: 0.6144 - acc: 0.7306
Epoch 4/100
120/120 [==============================] - 0s 537us/step - loss: 0.5962 - acc: 0.7500
Epoch 5/100
120/120 [==============================] - 0s 456us/step - loss: 0.5778 - acc: 0.7583
Epoch 6/100
120/120 [==============================] - 0s 456us/step - loss: 0.5601 - acc: 0.7611
Epoch 7/100
120/120 [==============================] - 0s 451us/step - loss: 0.5428 - acc: 0.7667
Epoch 8/100
120/120 [==============================] - 0s 473us/step - loss: 0.5253 - acc: 0.7694
Epoch 9/100
120/120 [==============================] - 0s 512us/step - loss: 0.5082 - acc: 0.7722
Epoch 10/100
120/120 [==============================] - 0s 546us/step - loss: 0.4925 - acc: 0.7778
Epoch 11/100
120/12

120/120 [==============================] - 0s 451us/step - loss: 0.1335 - acc: 0.9556
Epoch 84/100
120/120 [==============================] - 0s 460us/step - loss: 0.1322 - acc: 0.9583
Epoch 85/100
120/120 [==============================] - 0s 568us/step - loss: 0.1307 - acc: 0.9583
Epoch 86/100
120/120 [==============================] - 0s 551us/step - loss: 0.1292 - acc: 0.9583
Epoch 87/100
120/120 [==============================] - 0s 451us/step - loss: 0.1278 - acc: 0.9583
Epoch 88/100
120/120 [==============================] - 0s 378us/step - loss: 0.1264 - acc: 0.9583
Epoch 89/100
120/120 [==============================] - 0s 478us/step - loss: 0.1252 - acc: 0.9583
Epoch 90/100
120/120 [==============================] - 0s 426us/step - loss: 0.1237 - acc: 0.9583
Epoch 91/100
120/120 [==============================] - 0s 418us/step - loss: 0.1224 - acc: 0.9583
Epoch 92/100
120/120 [==============================] - 0s 418us/step - loss: 0.1211 - acc: 0.9583
Epoch 93/100
120/120 [=

In [15]:
ypred=classifier.predict(X_test)

In [18]:
import numpy as np
ypred_max=np.argmax(ypred, axis=1)

In [19]:
ypred_max

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0], dtype=int64)

In [22]:
y_test_max=np.argmax(y_test, axis=1)

In [23]:
y_test_max

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0], dtype=int64)

In [24]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_max,ypred_max))
print(confusion_matrix(y_test_max,ypred_max))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        11
          1       1.00      1.00      1.00        13
          2       1.00      1.00      1.00         6

avg / total       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
