In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

#### Data Explanation
#### ---------------------------
#### No Null values present in columns
#### Column: Explanation
##### fruit_label - Label given to each fruit name
##### fruit_name - name of the fruit, eg: Apple
##### fruit_subtype - sub type of fruit, eg: granny smith apple
##### mass - mass of the fruit
##### width - width of the fruit
##### height - height of the fruit
##### color_score - color_score of the fruit
#### ---------------------------

In [4]:
fruit_data=pd.read_table("data/fruit_data.txt")
fruit_data.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

### For data visualization and analysis visit https://github.com/beginmachinelearning/practice_exercises/blob/master/simple_fruit_classification/fruit_classification.ipynb

In [5]:
y=fruit_data['fruit_label']
X=fruit_data[['mass','width', 'height', 'color_score']]

In [17]:
y

0     1
1     1
2     1
3     2
4     2
5     2
6     2
7     2
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    3
25    3
26    3
27    3
28    3
29    3
30    3
31    3
32    3
33    3
34    3
35    3
36    3
37    3
38    3
39    3
40    3
41    3
42    3
43    4
44    4
45    4
46    4
47    4
48    4
49    4
50    4
51    4
52    4
53    4
54    4
55    4
56    4
57    4
58    4
Name: fruit_label, dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

Y = pd.get_dummies(y1).values

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [18]:
y_train

array([[0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1]], dtype=uint8)

In [1]:
import keras

from keras.models import Sequential
from keras.layers import Dense

classifier=Sequential()

Using TensorFlow backend.


In [2]:
classifier.add(Dense(8, input_dim=4, activation='relu'))
classifier.add(Dense(8, activation='relu'))
classifier.add(Dense(8, activation='relu'))
classifier.add(Dense(4, activation='softmax'))



In [3]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics = ['accuracy'])
classifier.fit(X_train, y_train, batch_size = 64, epochs = 500)


NameError: name 'X_train' is not defined

In [76]:
ypred=classifier.predict(X_test)

In [77]:
import numpy as np
ypred_max=np.argmax(ypred, axis=1)

In [78]:
y_test_max=np.argmax(y_test, axis=1)

In [79]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_max,ypred_max))
print(confusion_matrix(y_test_max,ypred_max))

             precision    recall  f1-score   support

          0       0.80      1.00      0.89         4
          1       1.00      1.00      1.00         1
          2       1.00      0.80      0.89         5
          3       1.00      1.00      1.00         2

avg / total       0.93      0.92      0.92        12

[[4 0 0 0]
 [0 1 0 0]
 [1 0 4 0]
 [0 0 0 2]]


In [80]:
from sklearn.metrics import accuracy_score
accuracy_score(ypred_max, y_test_max)

0.9166666666666666