In [16]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pylab as plt
from scipy import stats
from scipy.stats import norm
from scipy import stats
from scipy.stats import norm
from numpy import genfromtxt

In [17]:
X_train=pd.read_csv("data/train/X_train.txt",delim_whitespace=True, header=None)
y_train=pd.read_csv("data/train/y_train.txt",delim_whitespace=True, header=None)
X_test=pd.read_csv("data/test/X_test.txt",delim_whitespace=True, header=None)
y_test=pd.read_csv("data/test/y_test.txt",delim_whitespace=True, header=None)

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test1, y_train, y_test1= train_test_split(X_train, y_train, train_size=0.2)

F:\Anaconda\envs\tf-gpu\lib\site-packages\sklearn\model_selection\_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [20]:
X_train.shape

(1470, 561)

In [21]:
y_train[0].value_counts()

6    296
5    278
4    253
1    243
2    209
3    191
Name: 0, dtype: int64

In [22]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y_train)

Y = pd.get_dummies(y1).values

F:\Anaconda\envs\tf-gpu\lib\site-packages\sklearn\preprocessing\label.py:111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [23]:
Y

array([[0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0]], dtype=uint8)

In [24]:
import keras

from keras.models import Sequential
from keras.layers import Dense

classifier=Sequential()

In [25]:
classifier.add(Dense(100, input_dim=561, activation='relu'))
classifier.add(Dense(100,  activation='relu'))

classifier.add(Dense(6, activation='tanh'))



In [26]:
X_train.shape, Y.shape

((1470, 561), (1470, 6))

In [27]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics = ['accuracy'])
classifier.fit(X_train, Y, batch_size = 32, epochs = 50)



Epoch 1/50
1470/1470 [==============================] - 0s 334us/step - loss: 0.4502 - acc: 0.3494
Epoch 2/50
1470/1470 [==============================] - 0s 141us/step - loss: 0.1911 - acc: 0.2771
Epoch 3/50
1470/1470 [==============================] - 0s 143us/step - loss: 0.1439 - acc: 0.2635
Epoch 4/50
1470/1470 [==============================] - 0s 142us/step - loss: 0.1753 - acc: 0.2578
Epoch 5/50
1470/1470 [==============================] - 0s 145us/step - loss: 0.4806 - acc: 0.2277
Epoch 6/50
1470/1470 [==============================] - 0s 149us/step - loss: 0.8060 - acc: 0.1611
Epoch 7/50
1470/1470 [==============================] - 0s 140us/step - loss: 0.5666 - acc: 0.1624
Epoch 8/50
1470/1470 [==============================] - 0s 143us/step - loss: 0.5753 - acc: 0.1610
Epoch 9/50
1470/1470 [==============================] - 0s 133us/step - loss: 0.5331 - acc: 0.1568
Epoch 10/50
1470/1470 [==============================] - 0s 150us/step - loss: 0.5194 - acc: 0.1560
Epoch 11/

In [28]:
ypred=classifier.predict(X_test)


In [29]:
ypred

array([[-0.99953413, -0.9905202 , -0.99975055, -0.99999875,  0.99988705,
        -0.99995196],
       [-0.9984586 , -0.99607974, -0.9999733 , -1.        ,  0.98588234,
        -0.9999305 ],
       [-0.99996287, -0.9980158 , -0.9999868 , -1.        ,  0.8808941 ,
        -0.9999323 ],
       ...,
       [-0.6027662 ,  0.8174698 , -0.92579865, -0.99990904, -0.9980211 ,
        -0.9954184 ],
       [-0.81819105,  0.70897144, -0.44673032, -0.9960008 , -0.84335774,
        -0.994964  ],
       [ 0.765664  , -0.88340783, -0.58028746, -0.99921316, -0.9718182 ,
        -0.99705625]], dtype=float32)

In [30]:
import numpy as np
ypred_max=np.argmax(ypred, axis=1)
y_test_max=np.argmax(y_test, axis=1)

In [31]:
ypred_max

array([4, 4, 4, ..., 1, 1, 0], dtype=int64)

In [32]:
y_test_max

0
0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
...  ..
2917  0
2918  0
2919  0
2920  0
2921  0
2922  0
2923  0
2924  0
2925  0
2926  0
2927  0
2928  0
2929  0
2930  0
2931  0
2932  0
2933  0
2934  0
2935  0
2936  0
2937  0
2938  0
2939  0
2940  0
2941  0
2942  0
2943  0
2944  0
2945  0
2946  0

[2947 rows x 1 columns]

In [33]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_max,ypred_max))
print(confusion_matrix(y_test_max,ypred_max))

             precision    recall  f1-score   support

          0       1.00      0.18      0.31      2947
          1       0.00      0.00      0.00         0
          2       0.00      0.00      0.00         0
          4       0.00      0.00      0.00         0
          5       0.00      0.00      0.00         0

avg / total       1.00      0.18      0.31      2947

[[540 507 402 943 555]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0   0   0   0   0]]


F:\Anaconda\envs\tf-gpu\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(ypred_max, y_test_max)

In [36]:
y_test_max[0].value_counts(1)

0    1.0
Name: 0, dtype: float64

In [38]:
y_test_max[0]

0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
2917    0
2918    0
2919    0
2920    0
2921    0
2922    0
2923    0
2924    0
2925    0
2926    0
2927    0
2928    0
2929    0
2930    0
2931    0
2932    0
2933    0
2934    0
2935    0
2936    0
2937    0
2938    0
2939    0
2940    0
2941    0
2942    0
2943    0
2944    0
2945    0
2946    0
Name: 0, Length: 2947, dtype: int64