In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset_train = pd.read_csv('Google_Stock_Price_Train.csv')

In [3]:
dataset_train.shape

(1258, 6)

In [4]:
training_set=dataset_train.iloc[:, 1:2]

In [5]:
training_set

Open
0     325.25
1     331.27
2     329.83
3     328.34
4     322.04
5     313.70
6     310.59
7     314.43
8     311.96
9     314.81
10    312.14
11    319.30
12    294.16
13    291.91
14    292.07
15    287.68
16    284.92
17    284.32
18    287.95
19    290.41
20    291.38
21    291.34
22    294.23
23    296.39
24    302.44
25    303.18
26    304.87
27    302.81
28    304.11
29    304.63
...      ...
1228  766.92
1229  771.37
1230  762.61
1231  772.63
1232  767.73
1233  764.26
1234  760.00
1235  771.53
1236  770.07
1237  757.44
1238  744.59
1239  757.71
1240  764.73
1241  761.00
1242  772.48
1243  780.00
1244  785.04
1245  793.90
1246  797.40
1247  797.34
1248  800.40
1249  790.22
1250  796.76
1251  795.84
1252  792.36
1253  790.90
1254  790.68
1255  793.70
1256  783.33
1257  782.75

[1258 rows x 1 columns]

In [6]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler(feature_range=(0,1))

In [7]:
training_set_scaled=sc.fit_transform(training_set)

In [8]:
training_set_scaled

array([[ 0.08581368],
       [ 0.09701243],
       [ 0.09433366],
       ..., 
       [ 0.95725128],
       [ 0.93796041],
       [ 0.93688146]])

In [9]:
X_train=[]
y_train=[]

In [10]:
training_set_scaled.shape

(1258, 1)

In [11]:
for i in range(60, 1258):
    X_train.append(training_set_scaled[i-60:i, 0])
    y_train.append(training_set_scaled[i, 0])

In [12]:
X_train=np.array(X_train)
y_train=np.array(y_train)

In [13]:
X_train=np.reshape(X_train, (len(X_train), X_train.shape[1], 1))

In [14]:
X_train.shape[0]

1198

In [15]:
len(X_train)

1198

In [16]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

Using TensorFlow backend.


In [17]:
regressor=Sequential()

In [18]:
regressor.add(LSTM(units=50, return_sequences=True, input_shape=(X_train.shape[1], 1)))
regressor.add(Dropout(0.2))

In [19]:
regressor.add(LSTM(units=50, return_sequences=True))
regressor.add(Dropout(0.2))

In [20]:
regressor.add(LSTM(units=50, return_sequences=True))
regressor.add(Dropout(0.2))

In [21]:
regressor.add(LSTM(units=50))
regressor.add(Dropout(0.2))

In [22]:
regressor.add(Dense(units=1))

In [23]:
regressor.compile(optimizer='adam', loss='mean_squared_error')

In [24]:
regressor.fit(X_train, y_train, epochs=100, batch_size=32)

Epoch 1/100
1198/1198 [==============================] - 18s 15ms/step - loss: 0.0511
Epoch 2/100
1198/1198 [==============================] - 19s 16ms/step - loss: 0.0072
Epoch 3/100
1198/1198 [==============================] - 20s 17ms/step - loss: 0.0055
Epoch 4/100
1198/1198 [==============================] - 20s 17ms/step - loss: 0.0051
Epoch 5/100
1198/1198 [==============================] - 20s 17ms/step - loss: 0.0050
Epoch 6/100
1198/1198 [==============================] - 20s 17ms/step - loss: 0.0045
Epoch 7/100
1198/1198 [==============================] - 19s 16ms/step - loss: 0.0046
Epoch 8/100
1198/1198 [==============================] - 19s 16ms/step - loss: 0.0043
Epoch 9/100
1198/1198 [==============================] - 19s 16ms/step - loss: 0.0045
Epoch 10/100
1198/1198 [==============================] - 20s 16ms/step - loss: 0.0042
Epoch 11/100
1198/1198 [==============================] - 20s 16ms/step - loss: 0.0042
Epoch 12/100
1198/1198 [============================

1198/1198 [==============================] - 25s 21ms/step - loss: 0.0015
Epoch 96/100
1198/1198 [==============================] - 27s 23ms/step - loss: 0.0015
Epoch 97/100
1198/1198 [==============================] - 24s 20ms/step - loss: 0.0015
Epoch 98/100
1198/1198 [==============================] - 22s 18ms/step - loss: 0.0014
Epoch 99/100
1198/1198 [==============================] - 22s 19ms/step - loss: 0.0014
Epoch 100/100
1198/1198 [==============================] - 23s 19ms/step - loss: 0.0013


In [81]:
dataset_test = pd.read_csv('Google_Stock_Price_Test.csv')
real_stock_price=dataset_test.iloc[:, 1:2]

In [82]:
dataset_total=pd.concat((dataset_train['Open'], dataset_test['Open']), axis=0)
inputs=dataset_total[len(dataset_total)-len(dataset_test)-60:].values

In [87]:
inputs=inputs.reshape(-1,1)


In [88]:
len(inputs)

80

In [89]:
sc.transform(inputs)

array([[ 0.9299055 ],
       [ 0.93113327],
       [ 0.92750577],
       [ 0.94415507],
       [ 0.93876032],
       [ 0.93403527],
       [ 0.93483518],
       [ 0.9313937 ],
       [ 0.94636878],
       [ 0.96569685],
       [ 0.97510976],
       [ 0.95966962],
       [ 0.97808617],
       [ 1.        ],
       [ 0.98076494],
       [ 0.97083116],
       [ 0.98450406],
       [ 0.96054394],
       [ 0.9371419 ],
       [ 0.92841729],
       [ 0.90804747],
       [ 0.8771858 ],
       [ 0.92153434],
       [ 0.93809063],
       [ 0.93165414],
       [ 0.95254483],
       [ 0.88812412],
       [ 0.88637547],
       [ 0.87032145],
       [ 0.88563137],
       [ 0.90743359],
       [ 0.91571173],
       [ 0.89941588],
       [ 0.91805566],
       [ 0.9089404 ],
       [ 0.9024853 ],
       [ 0.89456061],
       [ 0.91600938],
       [ 0.9132934 ],
       [ 0.88979835],
       [ 0.86589404],
       [ 0.89030062],
       [ 0.90335962],
       [ 0.89642086],
       [ 0.91777662],
       [ 0

In [90]:
X_test=[]
for i in range(60, 80):
    X_test.append(inputs[i-60:i, 0])
    

In [91]:
X_test=np.array(X_test)

In [92]:
X_test=np.reshape(X_test, (len(X_test), X_test.shape[1], 1))

In [93]:
predicted_stock_price=regressor.predict(X_test)

In [94]:
predicted_stock_price

array([[-0.04841759],
       [-0.04841761],
       [-0.0484176 ],
       [-0.0484176 ],
       [-0.04841759],
       [-0.0484176 ],
       [-0.0484176 ],
       [-0.04841759],
       [-0.04841759],
       [-0.04841759],
       [-0.0484176 ],
       [-0.04841759],
       [-0.04841759],
       [-0.04841759],
       [-0.04841759],
       [-0.04841759],
       [-0.04841759],
       [-0.04841759],
       [-0.0484176 ],
       [-0.04841761]], dtype=float32)