In [1]:
import math
import numpy as np

In [2]:
x = np.array([2,3,1,0])

In [3]:
x

array([2, 3, 1, 0])

In [5]:
x.shape[0]

4

In [12]:
x[1]

3

In [6]:
x[1,2]

3

In [33]:
def one_hot_encoding(input_matrix):
    N=input_matrix.shape[0]
    k=max(input_matrix)
    Yout=np.zeros((N,k))
    for i in xrange(N):
        print(input_matrix[i])
        #print(i)
        Yout[i, input_matrix[i]-1]=1
    return Yout

In [34]:
k=one_hot_encoding(x)

2
3
1
0


In [35]:
x

array([2, 3, 1, 0])

In [36]:
k

array([[ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.]])