In [1]:
import math
import numpy as np

In [57]:
x = np.array([2,3,1,0])

In [3]:
x

array([2, 3, 1, 0])

In [5]:
x.shape[0]

4

In [12]:
x[1]

3

In [6]:
x[1,2]

3

In [41]:
def one_hot_encoding(input_matrix):
    N=input_matrix.shape[0]
    k=max(input_matrix)
    Yout=np.zeros((N,k+1))
    for i in xrange(N):
        print(input_matrix[i])
        #print(i)
        Yout[i, input_matrix[i]]=1
    return Yout

In [42]:
k=one_hot_encoding(x)

2
3
1
0


In [43]:
x

array([2, 3, 1, 0])

In [48]:
k.unique()

AttributeError: 'numpy.ndarray' object has no attribute 'unique'

In [45]:
np.argmax(k, axis=1)

array([2, 3, 1, 0])

In [51]:
x = np.array([2,3,2,0])

In [58]:
len(np.unique(x))

4

In [56]:
np.unique(x)

array([0, 2, 3])